sudo: true

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - cache

env:
  - IMAGINE_DRIVER=imagick
  - IMAGINE_DRIVER=gmagick

before_install:
  - PHP_INI_DIR="$HOME/.phpenv/versions/$(phpenv version-name)/etc/conf.d/"
  - TRAVIS_INI_FILE="$PHP_INI_DIR/travis.ini"
  - echo "memory_limit=2048M" >> "$TRAVIS_INI_FILE"

install:
  - |
    set -o errexit
    case "${TRAVISOPERATION-}" in
        codestyle)
            ;;
        *)
            sudo apt-get update
            sudo apt-get remove -y imagemagick libmagickcore-dev libmagickwand-dev
            sudo apt-get update -y || true
            sudo apt-get install -y ca-certificates libtiff-dev libjpeg-dev libdjvulibre-dev libwmf-dev pkg-config liblcms2-dev
            PHPUNIT_EXCLUDED_GROUPS=always-skipped
            if test "${IMAGINE_DRIVER}" = 'imagick'; then ./.travis/imagick.sh; else PHPUNIT_EXCLUDED_GROUPS="${PHPUNIT_EXCLUDED_GROUPS},ext-imagick"; fi
            if test "${IMAGINE_DRIVER}" = 'gmagick'; then ./.travis/gmagick.sh; else PHPUNIT_EXCLUDED_GROUPS="${PHPUNIT_EXCLUDED_GROUPS},ext-gmagick"; fi
            composer --no-interaction remove --dev --no-update --no-scripts friendsofphp/php-cs-fixer
            if [ "$TRAVIS_PHP_VERSION" == "7.2" ]; then wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar; fi
            ;;
    esac
  - php --ri curl || true
  - ifconfig || true
  - composer --no-interaction install

script:
  - |
    set -o errexit
    case "${TRAVISOPERATION:-}" in
        codestyle)
            composer --no-interaction codestyle -- --no-interaction --dry-run --diff -- .
            ;;
        *)
            if [ "$TRAVIS_PHP_VERSION" == "7.2" ]
            then
              composer --no-interaction test-coverage -- --exclude-group "${PHPUNIT_EXCLUDED_GROUPS}"
            else
              composer --no-interaction test -- --exclude-group "${PHPUNIT_EXCLUDED_GROUPS}"
            fi
            ;;
    esac

after_success:
  - |
    set -o errexit
    case "${TRAVISOPERATION:-}" in
        codestyle)
            ;;
        *)
            if [ "$TRAVIS_PHP_VERSION" == "7.2" ]; then php php-coveralls.phar -v; fi
            ;;
    esac

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
    - php: nightly
  include:
    - php: 5.3
      dist: precise
      env:
        - IMAGINE_DRIVER=imagick
    - php: 5.3
      dist: precise
      env:
        - IMAGINE_DRIVER=gmagick
    - php: 7.2
      env:
        - TRAVISOPERATION=codestyle
